### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by tamberg** [tamberg/fhnw-iot-bricks#29]
tamberg@mac Bricks8 % java -cp ./target:lib/org.eclipse.paho.client.mqttv3-1.2.3.jar:lib/fhnw-iot-bricks-0.0.1.jar Program
Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at ch.fhnw.imvs.bricks.mock.MockProxy.run(MockProxy.java:35)
	at ch.fhnw.imvs.bricks.mock.MockProxy$1.run(MockProxy.java:50)

**Comment by tamberg** [comment]
tamberg@mac Bricks8 % java -cp ./target:lib/org.eclipse.paho.client.mqttv3-1.2.3.jar:lib/fhnw-iot-bricks-0.0.1.jar Program
Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at ch.fhnw.imvs.bricks.mock.MockProxy.run(MockProxy.java:35)
	at ch.fhnw.imvs.bricks.mock.MockProxy$1.run(MockProxy.java:50)
